rust-stable:
  parallel:
    matrix:
      - PCI_DRIVER_FEATURES:
        - ""
        - vfio
  image: rust:latest
  before_script:
    - rustup component add clippy rustfmt
  script:
    - PCI_DRIVER_FEATURES+=,_unsafe-op-in-unsafe-fn ./test.sh

rust-1.47:
  extends: rust-stable
  image: rust:1.47
  script:
    - ./test.sh
