rust-stable:
  parallel:
    matrix:
      - IMAGE:
          - amd64/rust
          - i386/rust
        PCI_DRIVER_FEATURES:
          - ""
          - vfio
  image: $IMAGE:latest
  before_script:
    - rustup component add clippy rustfmt
  script:
    - PCI_DRIVER_FEATURES+=,_unsafe-op-in-unsafe-fn ./test.sh

rust-1.47:
  extends: rust-stable
  image: $IMAGE:1.47
  script:
    - ./test.sh
